title: Home (YAML)
custom_header:
  compact_mode: true
  header_text: '{{ states.sensor.time.state }}'
  exceptions:
    - conditions:
        user: Bildschirm
      config:
        background: "#202020"
        all_tabs_color: "#ff9c27"
        menu_color: "#ff9c27"
        voice_color: "#ff9c27"
        options_color: "#ff9c27"
        tab_indicator_color:  "#ff9c27"
        notify_indicator_color: "#eeeeee"

views:
  - !include home/01_home.yaml
  - !include home/02_climate.yaml
