---
- platform: template
  sensors:
    living_room_netatmo_lowbat:
      unique_id: "netatmo_livingroom_low_bat"
      value_template: >-
        {{ states('sensor.office_room_office_room_office_room_living_room_battery_percent') | float(0) < 5 }}
    kids_bedroom_netatmo_lowbat:
      unique_id: "netatmo_edwardsbedroom_low_bat"
      value_template: >-
        {{ states('sensor.office_room_office_room_office_room_edward_s_bedroom_battery_percent') | float(0) < 5 }}
    master_bedroom_netatmo_lowbat:
      unique_id: "netatmo_masterbedroom_low_bat"
      value_template: >-
        {{ states('sensor.office_room_office_room_office_room_master_bedroom_battery_percent') | float(0) < 5 }}
    outdoor_netatmo_lowbat:
      unique_id: "netatmo_outdoor_low_bat"
      value_template: >-
        {{ states('sensor.office_room_office_room_office_room_outdoor_battery_percent') | float(0) < 5 }}