---
- platform: template
  sensors:
    tradfri_sound_remote_living_room_low_bat:
      unique_id: "tradfri_sound_remote_living_room_low_bat"
      value_template: >-
        {{ states('sensor.sound_remote_living_room') | float(0) < 5 }}
    tradfri_sound_remote_office_room_low_bat:
      unique_id: "tradfri_sound_remote_office_room_low_bat"
      value_template: >-
        {{ states('sensor.sound_remote_office_room') | float(0) < 5 }}
    tradfri_shortcut_button_low_bat:
      unique_id: "tradfri_shortcut_button_low_bat"
      value_template: >-
        {{ states('sensor.shortcut_button') | float(0) < 5 }}
    tradfri_on_off_switch_low_bat:
      unique_id: "tradfri_on_off_switch_low_bat"
      value_template: >-
        {{ states('sensor.tradfri_on_off_switch') | float(0) < 5 }}
    tradfri_remote_control_low_bat:
      unique_id: "tradfri_remote_control_low_bat"
      value_template: >-
        {{ states('sensor.tradfri_remote_control') | float(0) < 5 }}