- id: 'beace735f1ea4ec0899dd6abe05391ea'
  alias: Send me garbage notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.garbagealert_papierabfuhr
  condition: []
  action:
  - service: notify.telegram_marco
    data:
      message: "{% set trigger = {\n  \"when\": trigger.to_state.state,\n  \"what\"\
        : trigger.to_state.attributes.friendly_name\n} %} {% if trigger.when == 'Today'\
        \ %}\n  {% set reminder = 'REMINDER: ' %}\n{% endif %}\n{{ reminder ~ trigger.when\
        \ }} is {{ trigger.what }}"
  mode: single

- id: 82a5b9a9369f46369e8d3ad4b8b50030
  alias: Device Tracker - Home Assistant Start create Guest Tracker
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:01:00
  - service: device_tracker.see
    data_template:
      dev_id: guests
      host_name: Guests
      location_name: '{% if is_state(''sensor.guest_count'', ''0'') -%} not_home {%-
        else -%} home {%- endif %}'

- id: 50b915ee8d20404480ac5d3284d0f66d
  alias: Device Tracker - Update Guest Tracker
  trigger:
  - platform: state
    entity_id: sensor.guest_count
  action:
  - service: device_tracker.see
    data_template:
      dev_id: guests
      host_name: Guests
      location_name: '{% if is_state(''sensor.guest_count'', ''0'') -%} not_home {%-
        else -%} home {%- endif %}'
  