- id: beace735f1ea4ec0899dd6abe05391ea
  alias: Send me garbage notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.garbagealert_papierabfuhr
  condition: []
  action:
  - service: notify.telegram_marco
    data:
      message: "{% set trigger = {\n  \"when\": trigger.to_state.state,\n  \"what\":
        trigger.to_state.attributes.friendly_name\n} %}\n\n{% if trigger.when == 'Today'
        %}\n  {% set reminder = 'REMINDER: ' %}\n{% endif %}\n\n{{ reminder ~ trigger.when
        }} is {{ trigger.what }}"
  mode: single
- id: '1682593100148'
  alias: 'Garage Door switch: ventilation'
  description: ''
  trigger: []
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.00131709ae3834
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.00131709ae3834
  mode: single
