# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  unit_system: !secret home_unitsystem
  currency: !secret home_currency
  country: !secret home_country
  external_url: !secret home_external_url
  internal_url: !secret home_internal_url

  # Load customizations
  customize: !include customize.yaml
  customize_glob:
    "binary_sensor.*door*":
      device_class: door
    "binary_sensor.*window*":
      device_class: window

  # Load packages/integrations
  packages: !include_dir_named packages

  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.10.0/24
        - 192.168.11.0/24
        - 192.168.100.0/24
        - 178.198.126.123/32
      trusted_users:
        192.168.10.50: !secret userid_marco
        192.168.10.51: !secret userid_marco

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Load device trackers
# device_tracker:

# Discover some devices automatically
#discovery:

hassio:

system_health:

# Track the sun
sun:

# Checks for available updates
# updater:
# Analytics reporting with the option 'include_used_components' is deprecated
# and you should remove that from your configuration. The analytics part of
# this integration has moved to the new 'analytics' integration
#include_used_components: true

mobile_app:

frontend:
  #themes: !include themes/themes.yaml
  themes: !include_dir_merge_named themes

# Load switches
switch: !include switches.yaml
# Load  sensors
sensor: !include_dir_merge_list ./entities/sensors/sensor/
# Load binary sensors
binary_sensor: !include_dir_merge_list ./entities/sensors/binary_sensor/

# Load lights:
light: !include_dir_merge_list ./entities/lights/

# Load Alarm
alarm_control_panel: !include_dir_merge_list ./entities/alarm/

# Load persons
person: !include_dir_merge_list ./entities/persons/
# Load zones
zone: !include zones.yaml

# Load helpers
input_boolean: !include_dir_merge_named ./helpers/input_boolean/
input_number: !include_dir_merge_named ./helpers/input_number/
input_select: !include_dir_merge_named ./helpers/input_select/
template: !include_dir_merge_list ./helpers/template/
group: !include_dir_merge_named ./helpers/groups/

# Load automations
#automation: !include automations.yaml
#automation split: !include_dir_merge_list ./automations
# Load scripts
script: !include scripts.yaml
# Load scenes
scene: !include scenes.yaml
# Load Rest commands
rest_command: !include_dir_merge_named rest_commands/

# Text to speech
tts:
  - platform: google_translate

api:

#system_health:

#python_script:

# https://www.home-assistant.io/integrations/logger
# log_level= critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: info
  # logs:
  #   homeassistant.core: info
  #   homeassistant.components.cast: info
  #   homeassistant.components.http: info
  #   homeassistant.components.mqtt: info
  #   homeassistant.components.pyhomematic: info
  #   homeassistant.components.python_script: info
  #   homeassistant.components.ipp: info
  #   homeassistant.components.shelly: info
  #   homeassistant.components.calendar: info
  #   homeassistant.components.device_tracker: info
  #   homeassistant.components.switch.template: info
  #   homeassistant.components.switch.command_line: info
  #   homeassistant.components.python_script.my_new_script.py: debug
  #   aioshelly: info
  #   googleapiclient.discovery: info
  #   hamsclient.client: info
  #   pychromecast.socket_client: info
  #   pyhomematic: warn
  #   volvooncall.volvooncall: info
  #   aiounifi: info
  #   homeassistant.components.unifi: info
  #   homeassistant.components.device_tracker.unifi: info
  #   homeassistant.components.switch.unifi: info

logbook:
  include:
    domains:
      - sensor
      # - binary_sensor
      - switch
      - media_player
      - update
    entities:
      # Balcony door
      - binary_sensor.0000d8a99e5ae7_state
    entity_globs:
      - binary_sensor.*_low_bat
      - binary_sensor.*_lowbat
  exclude:
    entities:
      - sensor.utc
      - sensor.date_time
    # entity_globs:
    #   - weather.*

lovelace:
  # mode can be either yaml or storage
  mode: yaml
  resources:
    - url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-digital-clock/digital-clock.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/light-entity-card/dist/light-entity-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/calendar-card-pro/calendar-card-pro.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
  dashboards: !include dashboards/dashboards.yaml

my:
