- platform: template
  sensors:
    guest_count:
      friendly_name: "Guest Count"
      value_template: >-
        {{ states.device_tracker | selectattr('attributes.is_guest', 'eq', true) | list | count }}

    garbagealert_altmetallabfuhr:
      unique_id: "garbagealert_altmetallabfuhr"
      friendly_name: "Altmetallabfuhr"
      icon_template: >
        {% if is_state('binary_sensor.altmetallabfuhr', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.altmetallabfuhr' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}

    garbagealert_gruenabfuhr:
      unique_id: "garbagealert_gruenabfuhr"
      friendly_name: "Grünabfuhr"
      icon_template: >
        {% if is_state('binary_sensor.gruenabfuhr', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.gruenabfuhr' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}

    garbagealert_kartonabfuhr:
      unique_id: "garbagealert_kartonabfuhr"
      friendly_name: "Kartonabfuhr"
      icon_template: >
        {% if is_state('binary_sensor.kartonabfuhr', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.kartonabfuhr' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}

    garbagealert_kehricht_und_sperrgut:
      unique_id: "garbagealert_kehricht_und_sperrgut"
      friendly_name: "Kehricht und Sperrgut"
      icon_template: >
        {% if is_state('binary_sensor.kehricht_und_sperrgut', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.kehricht_und_sperrgut' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}

    garbagealert_mineralische_abfaelle:
      unique_id: "garbagealert_mineralische_abfaelle"
      friendly_name: "Mineralische Abfälle"
      icon_template: >
        {% if is_state('binary_sensor.mineralische_abfaelle', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.mineralische_abfaelle' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}

    garbagealert_papierabfuhr:
      unique_id: "garbagealert_papierabfuhr"
      friendly_name: "Altpapier"
      icon_template: >
        {% if is_state('binary_sensor.papierabfuhr', 'on') %}
          mdi:delete-alert
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >-
        {% set update = states('sensor.date_time') %}
        {% set calendar = 'calendar.papierabfuhr' %}

        {% set midnight = now().date() | as_timestamp %}
        {% set event = state_attr(calendar,'start_time') | as_timestamp %}
        {% if event != None %}
          {% set delta = ((event - midnight) // 86400) | int %}
          {% set values = [ 'Today', 'Tomorrow', 'Day After Tomorrow' ] %}
          {{ values[delta] if delta < values | length else 'In %s Days'%delta }}
        {% else %}
          {{ "No event found" }}
        {% endif %}


- platform: time_date
  display_options:
    - 'date_time'

- platform: worldclock
  time_zone: Etc/UTC
  name: 'UTC'

#  // YML deprecated and requires new configuration //
# - platform: mqtt
#   state_topic: "home/officeroom/temperature"
#   name: "Temperature Office Sensor"
  
#  // Deprecated //
# - platform: google_travel_time
#   name: Travel home to office
#   #friendly_name: "Home to office"
#   api_key: !secret google_distance_api_key
#   origin: zone.home
#   destination: zone.work
#   scan_interval: 300