title: Home

views:
  - !include dashboards/legacy/01_home.yaml
  - !include dashboards/legacy/02_climate.yaml
  - !include dashboards/legacy/03_Audio.yaml
  - !include dashboards/legacy/20_settings.yaml
  - !include dashboards/legacy/30_byrooms.yaml
  - !include dashboards/legacy/30_bydomains.yaml
  - !include dashboards/legacy/30_allstates.yaml