title: Settings
path: settings
icon: mdi:cog
panel: true
cards:
  - type: 'custom:layout-card'
    layout: horizontal
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.0000d8a99e5ae7_low_bat
          - entity: binary_sensor.peq0478568_lowbat
          - entity: binary_sensor.00131709ae3834_low_bat
          - entity: binary_sensor.000a18a9a3c495_low_bat
          - entity: binary_sensor.000a18a996ee03_low_bat
          - entity: binary_sensor.000a1be9966275_low_bat
          - entity: binary_sensor.001198a99fac1e_low_bat
          - entity: binary_sensor.001198a99fac29_low_bat
          - entity: sensor.sm_g975f_battery_level
        title: Battery Levels
