title: Settings
path: settings
icon: mdi:cog
type: panel
# panel: true
cards:
  - type: 'custom:layout-card'
    layout: horizontal
    cards:
      - type: entities
        entities:
          - entity: sensor.sm_g998b_battery_level
          - entity: binary_sensor.0000d8a99e5ae7_low_bat
          - entity: binary_sensor.peq0478568_lowbat
          - entity: binary_sensor.00131709ae3834_low_bat
          - entity: sensor.office_room_office_room_office_room_living_room_battery_percent
          - entity: sensor.office_room_office_room_office_room_edward_s_bedroom_battery_percent
          - entity: sensor.office_room_office_room_office_room_master_bedroom_battery_percent
          - entity: sensor.office_room_office_room_office_room_outdoor_battery_percent
          - entity: sensor.sound_remote_living_room
          - entity: sensor.sound_remote_office_room
          - entity: sensor.shortcut_button
          - entity: sensor.tradfri_on_off_switch
          - entity: sensor.tradfri_remote_control
        title: Battery Levels
      # - type: entities
      #   entities:
      #     - entity: sensor.hue_dimmer_switch_1_battery_level
      #     - entity: sensor.sound_remote_office
      #     - entity: sensor.sound_remote_living_room
      #     - entity: sensor.tradfri_on_off_switch
      #   title: Other levels (WIP)
      - type: vertical-stack
        cards:
          - type: conditional
            conditions:
              - condition: state
                entity: group.updates_firmware
                state: 'on'
            card:
              type: custom:auto-entities
              card:
                type: entities
                title: Available Firmware Updates
              filter:
                template: |-
                  {{ expand('group.updates_firmware')|
                    selectattr('state','eq','on')|
                    map(attribute='entity_id')|
                    list|
                    sort|
                    join(', ')
                  }}
          - type: conditional
            conditions:
              - condition: state
                entity: group.updates_software
                state: 'on'
            card:
              type: custom:auto-entities
              card:
                type: entities
                title: Available Software Updates
              filter:
                template: |-
                  {{ expand('group.updates_software')|
                    selectattr('state','eq','on')|
                    map(attribute='entity_id')|
                    list|
                    sort|
                    join(', ')
                  }}
