- alias: Change Guests to "Away"
  description: ''
  trigger:
  - platform: state
    entity_id: person.guests
    from: home
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.guest_home
  mode: single
- alias: Change Guests to "At home"
  description: ''
  trigger:
  - platform: state
    entity_id: person.guests
    to: home
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.guest_home
  mode: single
