---
## Example configuration.yaml entry

- platform: template
  panels:
    home_alarm_panel:
      unique_id: 2f9141cf-e668-4303-9772-25674ef23a1b
      # value_template: "{{ states('alarm_control_panel.home_alarm') }}"
      arm_away:
        action: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.home_alarm
        data:
          code: 1234
      arm_home:
        action: alarm_control_panel.alarm_arm_home
        target:
          entity_id: alarm_control_panel.home_alarm
        data:
          code: 1234
      disarm:
        - condition: state
          entity_id: person.marco
          state: "Home"
        - action: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.home_alarm
          data:
            code: 1234