---
- platform: group
  name: Lights Master Bedroom
  unique_id: masterbedroom_lights
  entities:
    - light.masterbedroom_ceiling_lamp
    - light.marco_s_yeelight
    - light.sharene_s_yeelight

- platform: group
  name: Lights Kids Room
  unique_id: kidsroom_lights
  entities:
    - light.kidsroom_ceiling_lamp

- platform: group
  name: Lights Guest Room
  unique_id: guestroom_lights
  entities: []

- platform: group
  name: Lights Office
  unique_id: office_lights
  entities:
    - light.office_ceiling_lamp
    - light.office_led_strip

- platform: group
  name: Lights Living Room
  unique_id: livingroom_lights
  entities:
    - light.livingroom_ceiling_spotlights_main
    - light.livingroom_ceiling_spotlights_tv

- platform: group
  name: Lights Kitchen
  unique_id: kitchen_lights
  entities:
    - light.kitchen_ceiling_spotlights

- platform: group
  name: Lights Hallway
  unique_id: hallway_lights
  entities:
    - light.hallway_ceiling_spotlights
