---
- platform: group
  name: Lights Master Bedroom
  unique_id: masterbedroom_lights
  entities:
    - light.masterbedroom_ceiling_lamp
    - light.marco_s_yeelight
    - light.sharene_s_yeelight

- platform: group
  name: Lights Kids Bedroom
  unique_id: kidsbedroom_lights
  entities:
    - light.kidsbedroom_ceiling_lamp

- platform: group
  name: Lights Guest Bedroom
  unique_id: guestbedroom_lights
  entities: {}

- platform: group
  name: Lights Office Room
  unique_id: officeroom_lights
  entities:
    - light.officeroom_ceiling_lamp

- platform: group
  name: Lights Living Room
  unique_id: livingroom_lights
  entities:
    - light.livingroom_ceiling_spotlights_main
    - light.livingroom_ceiling_spotlights_tv

- platform: group
  name: Lights Kitchen
  unique_id: kitchen_lights
  entities:
    - light.kitchen_ceiling_spotlights

- platform: group
  name: Lights Hallway
  unique_id: hallway_lights
  entities:
    - light.hallway_ceiling_spotlights
